<?php

namespace AppBundle\Repository;

/**
 * Carte_mereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Carte_mereRepository extends \Doctrine\ORM\EntityRepository
{
}
