<?php

namespace AppBundle\Repository;

/**
 * cartProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cartProductRepository extends \Doctrine\ORM\EntityRepository
{
}
