<?php

namespace AppBundle\Repository;

/**
 * CpuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CpuRepository extends \Doctrine\ORM\EntityRepository
{
}
