<?php

namespace AppBundle\Repository;

/**
 * CpuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CpuRepository extends \Doctrine\ORM\EntityRepository
{
	    public function findProduct($key)
    {
         $em = $this->getEntityManager();
        //$query = $em->createQuery('SELECT u FROM AppBundle:Product u WHERE u.brand LIKE :name')
         $query = $this->createQueryBuilder('p')
        ->andWhere('p.designation LIKE :name OR p.brand LIKE :name OR p.size LIKE :name')
        ->setParameter('name', '%'.$key.'%')
        ->getQuery()
        ->getResult();
       
       
        return $query; 
    }
}
