<?php

namespace AppBundle\Repository;

/**
 * MemoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemoryRepository extends \Doctrine\ORM\EntityRepository
{
}
