<?php

namespace AppBundle\Repository;

/**
 * MotherBoardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotherBoardRepository extends \Doctrine\ORM\EntityRepository
{
}
