<?php

namespace AppBundle\Repository;

/**
 * PaiementTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaiementTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
