<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProduct($key)
    {
         $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT u FROM AppBundle:Product u WHERE u.brand LIKE :name');
        $query->setParameter('name', '%'.$key.'%');
        $result = $query->getResult();
       
        return $result; 

        

    }
}
